/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2023-02-06 10:57:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Iterator;
import test.employee.Employee;
import test.employee.RWEmpData;

public final class empList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");

String target = "";
if (session.getAttribute("ID") == null || !session.getAttribute("ID").equals("root")){
	target = "../login.html";
	response.sendRedirect(target);
}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction listView(userid){\r\n");
      out.write("\t    let f = document.createElement('form');\r\n");
      out.write("\t    \r\n");
      out.write("\t    let obj;\r\n");
      out.write("\t    obj = document.createElement('input');\r\n");
      out.write("\t    obj.setAttribute('type', 'hidden');\r\n");
      out.write("\t    obj.setAttribute('name', 'ID');\r\n");
      out.write("\t    obj.setAttribute('value', userid);\r\n");
      out.write("\t    \r\n");
      out.write("\t    f.appendChild(obj);\r\n");
      out.write("\t    f.setAttribute('method', 'get');\r\n");
      out.write("\t    f.setAttribute('action', 'empInfo.jsp');\r\n");
      out.write("\t    document.body.appendChild(f);\r\n");
      out.write("\t    f.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>사번</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>직위</th>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		RWEmpData rwe = new RWEmpData();
		HashMap<String, Employee> hmEmp = rwe.readEmps();
		Iterator<String> it = hmEmp.keySet().iterator();
		while(it.hasNext()){  // 맵키가 존재할경우
			String key = it.next();  // 맵키를 꺼냄
			Employee emp = (Employee)hmEmp.get(key);  // 키에 해당되는 객체 꺼냄
			String id = emp.getNo();
    		String name = emp.getName();
    		String level = emp.getLevel();
    		String phone = emp.getPhone();
     	
      out.write("\r\n");
      out.write("  \t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"javascript:listView('");
      out.print(id );
      out.write("')\">");
      out.print(id );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(level );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(phone );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t\r\n");
      out.write("      \t");

	    }
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
