/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2023-02-06 10:33:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class empRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");

String target = "";
if (session.getAttribute("ID") == null || !session.getAttribute("ID").equals("root")){
	target = "../login.html";
	response.sendRedirect(target);
}

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"con\">\r\n");
      out.write("    <div id=\"login\">\r\n");
      out.write("\t    <div id=\"login_form\"><!--로그인 폼-->\r\n");
      out.write("\t\t    <form method=\"get\" action=\"postRegister.jsp\">\r\n");
      out.write("\t\t        <h3 class=\"login\" style=\"letter-spacing:-1px;\">직원 정보 등록</h3>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <hr>\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t        사번\r\n");
      out.write("\t\t        <input type=\"text\" name=\"no\" placeholder=\"사번\" class=\"size\" />\r\n");
      out.write("\t\t        </label><!--아이디-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <label>\r\n");
      out.write("\t\t        이름 \r\n");
      out.write("\t\t        <input type=\"text\" name=\"name\" placeholder=\"이름\" class=\"size\">\r\n");
      out.write("\t\t        </label><!--비밀번호-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t        직위 \r\n");
      out.write("\t\t        <select name=\"level\">\r\n");
      out.write("\t\t        \t<option value=\"Manager\">Manager</option>\r\n");
      out.write("\t\t\t\t    <option value=\"Engineer\">Engineer</option>\r\n");
      out.write("\t\t\t\t    <option value=\"Sales\">Sales</option>\r\n");
      out.write("\t\t        </select>\r\n");
      out.write("\t\t        </label><!--비밀번호-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t        전화번호\r\n");
      out.write("\t\t        <input type=\"text\" name=\"phone\" class=\"size\">\r\n");
      out.write("\t\t        </label><!--비밀번호-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t        취미 \r\n");
      out.write("\t\t        <input type=\"checkbox\" name=\"\">문화\r\n");
      out.write("\t\t        <input type=\"checkbox\" name=\"\">스포츠\r\n");
      out.write("\t\t        <input type=\"checkbox\" name=\"\">기타\r\n");
      out.write("\t\t        </label><!--비밀번호-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t        비고\r\n");
      out.write("\t\t\t\t<textarea rows=\"\" cols=\"\"></textarea>\r\n");
      out.write("\t\t        </label><!--비밀번호-->\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t    <button type=\"submit\">작성완료</button>\r\n");
      out.write("\t\t    <button type=\"reset\">취소</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t    \r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
