/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2023-01-25 07:34:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import emp.Emp;

public final class postLogin3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      emp.Emp emp = null;
      synchronized (session) {
        emp = (emp.Emp) _jspx_page_context.getAttribute("emp", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (emp == null){
          emp = new emp.Emp();
          _jspx_page_context.setAttribute("emp", emp, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("emp"), request);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");

System.out.println("emp data :: \n"+ emp);
String id = request.getParameter("id");
String pwd = request.getParameter("password");

if(id == null || pwd == null || id.equals("")||pwd.equals(""))
{

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("login.html");
        return;
      }
      out.write('\r');
      out.write('\n');

}
//로그인이 되어 있는지 체크
//if(emp.getId() == null || emp.getId().equals(""))

//새로 로그인을 할 경우
if (emp.getId().equals("root") && emp.getPassword().equals("admin"))
{ // 로그인 완료


      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((emp.Emp)_jspx_page_context.findAttribute("emp")).getId())));
      out.write("님의 Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"hello.html\">홈으로</a> &nbsp; &nbsp; &nbsp;\r\n");
      out.write("<a href=\"listBbs.jsp\">게시판가기</a><br>\r\n");
      out.write("<p>\r\n");
      out.write("환영합니다.<br>\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((emp.Emp)_jspx_page_context.findAttribute("emp")).getId())));
      out.write("님<br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
  // root/admin
}else
{

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("login.html");
        return;
      }
      out.write('\r');
      out.write('\n');

}

      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
